export enum TagType {
    SKILL = <any> "SKILL",
    SDG = <any> "SDG",
    MATERIALRESOURCE = <any> "MATERIALRESOURCE",
    REPORTPROFILE = <any>'REPORTPROFILE',
    REPORTGROUP = <any>'REPORTGROUP',
    REPORTPROJECT = <any>'REPORTPROJECT',
    REPORTPOST = <any>'REPORTPOST',
    REPORTCOMMENT = <any>'REPORTCOMMENT'
}